version: '3.8'

services:
    
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456
        POSTGRES_DB: phonebook-contactDB



  contactservice.api:
    build:
        context: .
        dockerfile: ./src/Services/ContactService/ContactService.API/Dockerfile
    ports:
    - "5000:80"
    depends_on:
    - postgres
    environment:
    - ConnectionStrings__postgres=Host=postgres;Port=5432;Database=phonebook-contactDB;User Id=postgres;Password=123456;Timeout=15;
    - ASPNETCORE_ENVIRONMENT=Development